let digit = 100;
if( digit == 1) console.log("Unit");
    else if( digit == 10) console.log("Ten");
    else if( digit == 100) console.log("Hundred");
    else if( digit == 1000) console.log("Thousand");
    else if( digit == 10000) console.log("Ten Thousand");
    else if( digit == 100000) console.log("Lakh");
    else if( digit == 1000000) console.log("Ten Lakh");
    else if( digit == 10000000) console.log("Crore");
    else if( digit == 100000000) console.log("Ten Crore");
    else console.log("Invalid number.");